version: "3.9"

services:
  protobuf-compiler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROTOBUF_VER=3.19.4
      target: goenv
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - PROTOBUF_GO_IMPORT_PREFIX=github.com/go-serv/utils/internal/autogen/proto
      - PROTO_TARGETS=go,commonjs
      - PROTO_COMPILE_DELAY=1000 # Debounce changes of the proto files for the specified amount of time before compiling, ms
    volumes:
      - type: bind
        source: ./internal/autogen/proto
        target: /app/proto/go
      - type: bind
        source: ./web/js
        target: /app/proto/commonjs
      - type: bind
        source: ./api
        target: /share # default directory for proto files