version: "3.9"

services:
  pb-samples:
    image: pb-compiler
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - PROTO_GO_IMPORT_PREFIX=github.com/mesh-master/mesh-master/internal/autogen
      - PROTO_COMPILE_DELAY=1000 # Debounce changes of the proto files for the specified amount of time before compiling, ms
    network_mode: host
    volumes:
      - type: bind
        source: ./proto
        target: /proto/source
      - type: bind
        source: ./autogen/nanopb
        target: /proto/autogen/nanopb
      - type: bind
        source: ./autogen/go
        target: /proto/autogen/go